### ISSUE TITLE
allow gitlab subgroups

### ISSUE THREAD

**Issue by benedikt-bartscher** [numberly/gitlab2sentry#7]
currently subgroups like group/subgroup/repository are not recognized by gitlab2sentry

**Comment by Solvik** [comment]
Hi! 

Thanks for your interest in the project!

We currently use this pattern and it works. Even with multiple subgroups 
There is still an issue with very long strings (ie: multiple subgroups and long project names) due to the limit of a project name in Sentry 

Would you be able to share the error you have?

Thanks!

**Comment by benedikt-bartscher** [comment]
Hi there, thanks for your quick reply and your awesome work!
You are right, subgroups are not the problem. gitlab2sentry only recognizes 9 repos, there are many more even in our top-level-group. Any ideas why only 9 Projects are fetched?

```
2022-11-04 11:53:06 root INFO: <Gitlab2Sentry>: Fetched 1 pages. Total time: 5.09 seconds
2022-11-04 11:53:06 root INFO: <Gitlab2Sentry>: Total filtered projects: 9
```

**Comment by thepetk** [comment]
Hi @benedikt-bartscher we have 2 variables that define the GraphQL query on gitlab

`group_identifier`: We define a key-word for our group
 `creation_days_limit`: Projects older that this limit will not be fetched.
 
 Maybe you are experience this because of one of those values?

**Comment by benedikt-bartscher** [comment]
nevermind, i am stupid. I changed creation_days_limit but the "IfNotPresent" policy didnt pull a new image for me. Thanks anyways for your help, i appreciate it!
